# #defaultTitle
#
##defaultDescription
#
#The version of the OpenAPI document: 0.1
#
#Generated by: https://openapi-generator.tech
#OpenAPI Generator version: 5.0.1
#

require "../spec_helper"
require "json"
require "time"

# Unit tests for ::DefaultApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe "DefaultApi" do
  describe "test an instance of DefaultApi" do
    it "should create an instance of DefaultApi" do
      api_instance = ::DefaultApi.new
      # TODO expect(api_instance).to be_instance_of(::DefaultApi)
    end
  end

  # unit tests for orgs_org_repos_get
  # All repos for an org
  # @param org 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe "orgs_org_repos_get test" do
    it "should work" do
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  # unit tests for repos_org_repo_assignees_get
  # All assignees to an org repo
  # @param org 
  # @param repo 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe "repos_org_repo_assignees_get test" do
    it "should work" do
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  # unit tests for repos_org_repo_commits_get
  # All commits on an org repo
  # @param org 
  # @param repo 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe "repos_org_repo_commits_get test" do
    it "should work" do
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  # unit tests for repos_org_repo_issues_events_get
  # all issue events on org repo
  # @param org 
  # @param repo 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe "repos_org_repo_issues_events_get test" do
    it "should work" do
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  # unit tests for repos_org_repo_issues_get
  # Get issues for org repo
  # @param org 
  # @param repo 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe "repos_org_repo_issues_get test" do
    it "should work" do
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  # unit tests for repos_org_repo_issues_issue_number_events_get
  # Events on org repo issue
  # @param org 
  # @param repo 
  # @param issue_number 
  # @param [Hash] opts the optional parameters
  # @return [String]
  describe "repos_org_repo_issues_issue_number_events_get test" do
    it "should work" do
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  # unit tests for repos_org_repo_issues_issue_number_timeline_get
  # Get timeline of org repo issue
  # @param org 
  # @param repo 
  # @param issue_number 
  # @param [Hash] opts the optional parameters
  # @return [String]
  describe "repos_org_repo_issues_issue_number_timeline_get test" do
    it "should work" do
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  # unit tests for repos_org_repo_labels_get
  # All labels on an org repo
  # @param org 
  # @param repo 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe "repos_org_repo_labels_get test" do
    it "should work" do
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  # unit tests for repos_org_repo_milestones_get
  # Get all milestones for org repo
  # @param org 
  # @param repo 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe "repos_org_repo_milestones_get test" do
    it "should work" do
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  # unit tests for repos_org_repo_pulls_get
  # All pull requests on org repo
  # @param org 
  # @param repo 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe "repos_org_repo_pulls_get test" do
    it "should work" do
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  # unit tests for repos_org_repo_pulls_pull_number_reviews_get
  # Reviews on org repo pull request
  # @param org 
  # @param repo 
  # @param pull_number 
  # @param [Hash] opts the optional parameters
  # @return [String]
  describe "repos_org_repo_pulls_pull_number_reviews_get test" do
    it "should work" do
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  # unit tests for repos_org_repo_stats_contributors_get
  # Contributor stats on org repo
  # @param org 
  # @param repo 
  # @param [Hash] opts the optional parameters
  # @return [String]
  describe "repos_org_repo_stats_contributors_get test" do
    it "should work" do
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

end
